# Key bindings

bind-key L split-window -h
bind-key J split-window -v

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Bind zooming into a pane to prefix + f
bind-key f resize-pane -Z
