#!/usr/bin/env bash

main() {
  local contexts=$(kubectl config get-contexts -o name)
  local selected_context=$(echo "$contexts" | fzf --height=10%)

  if [ -n "$selected_context" ]; then
    kctx "$selected_context"
  fi
}

kctx() {
  if [[ -z "$1" ]]; then
    echo "Usage: kctx <context>"
    return 1
  fi

  if [[ "$1" == "-" ]]; then
    if [[ -z "$PREV_KUBECONTEXT" ]]; then
      echo "No previous context found."
      return 1
    fi
    local current_context="$KUBECONTEXT"
    export KUBECONTEXT="$PREV_KUBECONTEXT"
    export PREV_KUBECONTEXT="$current_context"
    echo "Switched back to previous context: $KUBECONTEXT"
    return 0
  fi

  local context="$1"
  local found_context=false
  if kubectl config get-contexts -o name | grep -q "$context"; then
    found_context=true
  fi

  if "$found_context"; then
    export KUBECONTEXT="$context"
    kubectl config use-context $context
    return 0
  else
    echo "Context $context not found in any of the files in KUBECONFIG=$KUBECONFIG"
    return 1
  fi
}

main
